#! /bin/bash
# Copyright (C) 2015.
# IFG
#
# Author: Marco Antônio Queiroz <marco.queiroz@ifg.edu.br>
#
# print
#
# System startup script for the ipr init facility
#
### BEGIN INIT INFO
# Provides: iprinit
# Required-Start:    $local_fs
# Should-Start:      $remote_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the ipr init daemon
# Description:       Start the ipr initialization daemon
### END INIT INFO
#
# chkconfig: 2345 20 80
# description: Servidor de Impressão
# processname: print
#

function findProcess(){
	ps aux | 
	egrep print/reload_logs.service\|print/reload_print.service\|print/reload_status.service |
	grep -v grep;
}

function start(){
	findProcess || {
		/opt/print/reload_logs.service &>/dev/null &
		/opt/print/reload_print.service &>/dev/null &
		/opt/print/reload_status.service &>/dev/null &
		echo "Active: success."
	}
}

function stop(){
	process=$( 
		findProcess | 
		awk '{print "kill " $2}'
	);
	echo -e "$process";
	$process &>/dev/null &&
	echo "Stop: success.";
}

function status(){
	findProcess && 
	echo "Active: success." || 
	echo "Active: failed.";
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	status)
		status;
	;;
	*)
		echo $"Use: {start|stop|restart|status}" 
		exit 2
esac
exit 0;